# Generated by Django 5.2.6 on 2025-12-09 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_account_balance_alter_transaction_instrument_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='shares',
        ),
        migrations.AddField(
            model_name='instrument',
            name='digits',
            field=models.IntegerField(default=2, help_text='Number of decimal places (e.g. 5 for EURUSD)'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='volume',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='account',
            name='balance',
            field=models.DecimalField(decimal_places=8, default=0.0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='current_price',
            field=models.DecimalField(decimal_places=8, max_digits=18),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='price',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=18),
        ),
    ]
