# Generated by Django 5.2.6 on 2025-12-10 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_transaction_shares_instrument_digits_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='commission',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='transaction',
            name='position_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
