# Generated by Django 5.2.6 on 2025-12-11 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_transactiontype_remove_transaction_position_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='average_price',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='position',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='position',
            name='volume',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=18),
        ),
    ]
